import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import Modal from "./components/modal/Modal";
import LoginModal from "./components/modal/LoginModal";
import SignupModal from "./components/modal/SignupModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MeeUK",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const content = (<p> Yoyo</p>)

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className="pt-[100px]">
          {children}
        </div>
        {/* <Modal
          label="Modal test"
          content={content}
          isOpen={false}
        /> */}
        <LoginModal />
        <SignupModal />
      </body>
    </html>
  );
}
